version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: dragin-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - http.port=9200
      - transport.tcp.port=9300
    network_mode: host
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  dragin:
    build: .
    container_name: dragin-app
    depends_on:
      elasticsearch:
        condition: service_healthy
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./result:/app/result
      - ./config:/app/config
      - ./src:/app/src
      - huggingface_cache:/root/.cache/huggingface
    environment:
      - ELASTICSEARCH_HOST=localhost
      - ELASTICSEARCH_PORT=9200
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  elasticsearch_data:
  huggingface_cache:
